### ISSUE TITLE
Data Scraping

### ISSUE THREAD

**Issue by JaxSulav** [JaxSulav/PriceProphet#1]
Data Scraping from e-commerce website

**Comment by JaxSulav** [comment]
#2 Backlog
- [ ] Research about the produtcs and categories to select
- [ ] Research about the specific attributes of products to scrape
- [ ] Research about the scraping tools, choose one
- [ ] Work on data scraping code
- [ ] Execute Scraping
